[versions]
kotlin = "2.2.21"
coroutines = "1.11.0"
serialization = "1.9.0"
teamcity = "2026.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
teamcity-agent-api = { module = "org.jetbrains.teamcity:agent-api", version.ref = "teamcity" }
teamcity-common-api = { module = "org.jetbrains.teamcity:common-api", version.ref = "teamcity" }
teamcity-tests-support = { module = "org.jetbrains.teamcity:tests-support", version.ref = "teamcity" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
arrow-core = { module = "io.arrow-kt:arrow-core", version = "2.2.2" }
commons-configuration = { module = "org.apache.commons:commons-configuration2", version = "2.15.1" }

mockk = { module = "io.mockk:mockk", version = "1.14.9" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.14.4" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.14.4" }
constraint-transitive-icu4j = { module = "com.ibm.icu:icu4j", version = { require = "3.4.4" } }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
